### ISSUE TITLE
a314fs crashes with yellow screen if directory does not exist

### ISSUE THREAD

**Issue by gmcn42** [niklasekstrom/a314#60] opened 2020-12-09 16:00 UTC
Hi everyone!

First off: great work, I'm really impressed by the whole project, especially the professional-looking hardware design!

Today I tried to get mine working, it's a Rev. 1.1 I bought off AmiBay.
My System: A500+, Kick 3.1, TF536 68030/50MHz, Indivision ECS V2

The A314 is jumpered to 2MB mode and Amiga Test Kit is reporting 2M Chip, memory test runs flawless. INT2 is connected.

After working out I had to explicitly enable the SPI bus on the Pi, I was able to use the pi command and videoplayer.

![pi_cmd](https://user-images.githubusercontent.com/3235799/101653269-6e21ed80-3a3f-11eb-956b-e9b8af4193e1.jpg)
![vidply](https://user-images.githubusercontent.com/3235799/101653388-90b40680-3a3f-11eb-853e-c47b1ce54ca4.jpg)

When I try to use a314fs, though, the Amiga crashes (Blinking LED of death, Yellow Screen).

![guru](https://user-images.githubusercontent.com/3235799/101653656-d7096580-3a3f-11eb-8569-5124b0ee403b.jpg)

`mount PI0:` seems to work fine but once I either `cd PI0:` or click `PI0:` in DirOpus, the crash occurs.

<del>Any idea how I can narrow down what's wrong? I thought about removing the accelerator and trying it on plain 68000 but I'd have to scavenge the CPU from another machine.</del>

**EDIT2:** Sorry, nevermind, **my fault**. I had to copy `a314fs.conf` file to `/opt/a314` and create the a314shared directory. Now everything works fine. I am leaving this issue up though as I believe a314fs should handle this error more gracefully than throwing a Guru. Also apparently I can report compatibility between A314 and TF536, yay! :)

EDIT: a314eth.device is working great as well (even with an old version of MiamiDX I had lying around). <del>So I guess if a314fs refuses to work with my setup, FTP file transfer is just fine.</del> :)

**Comment by niklasekstrom** [comment] 2020-12-10 09:13
Hi @gmcn42,

First, well done with the troubleshooting and great to hear that everything is finally working well! We can add both A314+TF536 and a314eth+MiamiDX to the "tested and seems to work" list :)

Secondly, this is definitively a bug that should be fixed, so thanks for reporting it. That the Amiga crashes with a yellow screen is a bit surprising (and interesting!). I suppose it should be a simple fix though, to check in a314fs.py if the shared directory exists, and if not then perhaps create it, or print a helpful error message (and certainly not crash).

A related thing that has been talked about, but no one got around to (yet), is to write a small program that installs the software needed on the Pi, and verifies that all files and configurations are as they should.

**Comment by cnilsson** [comment] 2021-08-13 01:05
I've reproduced this using kickstart 2.0 (albeit without the yellow screen - guru "only").

There is no error handling when there is no a314shared directory leading to a314fs.py throwing an exception and bailing out and thus stops responding to requests. The easiest way to fix this is probably to have a314fs.py create the directory as suggested. It looks like @niklasekstrom already had plans to handle problems such as a non responsive a314fs in a314fs.c but understandably moved on since everything worked.

**Comment by niklasekstrom** [comment] 2023-08-13 12:51
An installer script has been added, that amongst other things creates an a314shared directory.

Possibly/probably the code for a314fs should handle that the a314shared directory is missing, but I'll close this issue for now in any case.

**Closed by niklasekstrom** 2023-08-13 12:51 UTC
